### ISSUE TITLE
Crash on Manjaro

### ISSUE THREAD

**Issue by dastious** [Cybolic/LinReaper#3]
I don't know if it the same of the other issue, but I think it have a more comprehensive log.
On Manjaro (Arch based), when I click on forward 

```
Sauvegarde en : « /tmp/linreaper-reaper-install.exe »

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./main.py", line 206, in run_process
    main.widgets['progressbar_install'].set_fraction( float(procent) / 100 )
ValueError: could not convert string to float: /tmp/linreaper-reap
```

**Comment by Cybolic** [comment]
Wow, that's an interesting one; thanks for reporting it!
